// Catálogo Digital Print Maquinaria Gráfica — datos extraídos de digitalprintmaquinariagrafica.com
const CATALOG = [

// ============ LAMINADO / PLASTIFICADORAS ============
{cat:"laminado", model:"DPLASW 560/660/760", tagline:"Laminadora automática", desc:"Formato reducido y alta velocidad de puesta en marcha, ideal para empezar o renovar en laminado.",
 badges:["Vel. 0–60 m/min","Preparación 5 min","Formatos 560/660/760"],
 specs:[["Tamaño máx. hoja","560–760 × 820 mm"],["Espesor hoja","90–600 g/m²"],["Potencia","20/12 kW"],["Peso","2.600–3.000 kg"]]},
{cat:"laminado", model:"DPLASWAFM 1050/820", tagline:"Laminadora automática", desc:"Alta velocidad y formato modular para puesta en marcha, mantenimiento y preparación rápidos.",
 badges:["Vel. 0–80 m/min","Preparación 5 min","Modular"],
 specs:[["Tamaño máx. hoja","1050×820 / 820×1050 mm"],["Espesor hoja","90–600 g/m²"],["Potencia","35/18 kW"],["Peso","3.800–4.000 kg"]]},
{cat:"laminado", model:"DPLASW 1080", tagline:"Laminadora automática", desc:"Alta velocidad, bajo mantenimiento; calentador electromagnético listo en 5 minutos.",
 badges:["Vel. 0–100 m/min","Preparación 5 min","Opcionales disponibles"],
 specs:[["Tamaño máx. hoja","1080×900 a 1080×1450 mm"],["Espesor hoja","100–500 g/m²"],["Potencia","45 kW"],["Peso","6.400–6.800 kg"]]},
{cat:"laminado", model:"DPLA Serie G", tagline:"Laminadora automática (pila alta)", desc:"Versátil de pila alta para trabajos de larga producción y laminado a alta velocidad.",
 badges:["Vel. 0–120 m/min","Gran producción","Preparación 7 min"],
 specs:[["Tamaño máx. hoja","1050×820 a 1200×1650 mm"],["Espesor hoja","90–600 g/m²"],["Potencia","40/20–55/25 kW"],["Peso","7.000–9.500 kg"]]},
{cat:"laminado", model:"DPLASF 720C", tagline:"Laminadora semiautomática", desc:"Sencilla y compacta, perfecta para tareas de laminado con acabados de gran calidad.",
 badges:["Vel. 0–30 m/min","Compacta","Calentamiento 5 min"],
 specs:[["Ancho máx.","720–1100 mm"],["Espesor hoja","100–500 g/m²"],["Potencia","18–20 kW"],["Peso","1.700–2.100 kg"]]},
{cat:"laminado", model:"DPLAGL 1080", tagline:"Laminadora base agua", desc:"Apta para laminación térmica con film pre-revestido, cola base agua y film sin recubrir.",
 badges:["Vel. 0–100 m/min","Cola base agua","Preparación 7 min"],
 specs:[["Tamaño máx. hoja","1080×900 a 1450×1650 mm"],["Espesor hoja","100–500 g/m²"],["Potencia","100/50–120/60 kW"],["Peso","9.000–14.500 kg"]]},
{cat:"laminado", model:"DPLA-2020B", tagline:"Laminadora automática DRY (cartón ondulado)", desc:"Film térmico en seco; alimentación, laminación y corte automáticos en un proceso continuo.",
 badges:["Vel. 0–45 m/min","Ancho máx. 1950 mm","Sencilla"],
 specs:[["Temperatura laminado","100–180 °C"],["Potencia","25 kW"],["Peso","3.500 kg"],["Dimensiones","5700×2800×1600 mm"]]},

// ============ BARNIZADORAS ============
{cat:"barnizado", model:"Barnizadora DPBGV 1080", tagline:"Barnizadora UV/agua", desc:"Versátil con o sin opcionales, alta velocidad; recubrimiento preciso y uniforme.",
 badges:["Vel. 0–80 m/min","Preparación 7 min","Opcionales disponibles"],
 specs:[["Tamaño máx. pliego","1080×1080 a 1450×1650 mm"],["Gramaje","200–600 g/m²"],["Potencia","75–100 kW"],["Peso","6.500–9.000 kg"]]},
{cat:"barnizado", model:"Barnizadora DPIST-105 GS", tagline:"Barnizadora UV/IR spot-completo", desc:"Recubrimiento UV e IR de alta velocidad tipo spot o completo, con pantallas o planchas flexo.",
 badges:["10.000 pliegos/h","Sencilla","Área máx. 730×1050 mm"],
 specs:[["Tamaño máx. papel","740×1060 mm"],["Gramaje","80–600 g/m²"],["Potencia","IR 42 kW / UV 42 kW"],["Peso","13.700 kg"]]},

// ============ TROQUELADORAS ============
{cat:"troquelado", model:"Troqueladora DPTA-1060H", tagline:"Troqueladora automática sin stripping", desc:"Alta velocidad, sin stripping, pensada para rapidez, fiabilidad y costes ajustados.",
 badges:["7.500 pliegos/h","Precisión ±0,12 mm","Opcionales disponibles"],
 specs:[["Tamaño máx. pliego","1070×770 mm"],["Presión máx.","300 T"],["Potencia","19,5 kW"],["Peso","17.000 kg"]]},
{cat:"troquelado", model:"DPTAJY 106EBR", tagline:"Troqueladora automática con stripping y blanking", desc:"Sistema de stripping para packaging y transformación de cartón; carga sin parada.",
 badges:["6.500 pliegos/h","Sistema stripping","Interfaz intuitiva"],
 specs:[["Tamaño máx. pliego","1060×760 mm"],["Presión máx.","260 T"],["Potencia total","28 kW"],["Peso","22 T"]]},
{cat:"troquelado", model:"DPTAZHM 1670QE", tagline:"Troqueladora automática (cartón ondulado)", desc:"Troquelado industrial sobre cartón ondulado con doble cadena de aleación de aluminio.",
 badges:["4.000–4.500 pliegos/h","Alimentación continua","Sistema eléctrico inteligente"],
 specs:[["Tamaño máx. troquelado","1650×1200 mm"],["Presión máx.","300 T"],["Potencia motor","40 kW"],["Peso","24 T"]]},
{cat:"troquelado", model:"Máquina Automática para Cortar Hendidos (DPCH-C3)", tagline:"Cortadora automática de hendidos", desc:"Interpreta planos CAD y corta contrahendidos con un solo clic; acepta rollo, ahorra consumibles.",
 badges:["Hasta 50 cortes/min","Memoria 500 trabajos","Margen error <0,2 mm"],
 specs:[["Espesor contrahendido","0,3–3 mm"],["Sistema","Windows"],["Corriente","220V 50Hz"],["Peso","60 kg"]]},
{cat:"troquelado", model:"9000 PRO", tagline:"Troqueladora automática 2025", desc:"Gama de alto rendimiento; procesa desde papel 90 g/m² hasta cartón ondulado 2000 g/m².",
 badges:["9.000 pliegos/h","Función No-Stop","Control por servomotores"],
 specs:[["Formato máx.","1050×750 mm"],["Presión máx.","400 T"],["Consumo energía","20 kW"],["Peso neto","17 T"]]},

// ============ ROBOTS DE PELADO ============
{cat:"robots-pelado", model:"DPTASM 1020", tagline:"Robot de pelado", desc:"Cargador con pre-pelado, servomotores y sistema hidráulico con inverter para pelado continuo.",
 badges:["12–15 golpes/min","Alimentación automática","Interfaz táctil"],
 specs:[["Pliego máx.","1100×960 mm"],["Producto a pelar","60×400 a 200×850 mm"],["Fuerza máx.","70 bar"],["Peso","3.500 kg"]]},
{cat:"robots-pelado", model:"DPTASM 1080", tagline:"Robot de pelado (stripping automático)", desc:"Limpiadora de pliegos desde papel a cartón ondulado; memoria de 500 trabajos.",
 badges:["0–25 veces/min","Memoria 500 trabajos","Opcionales disponibles"],
 specs:[["Hoja máx.","1080×780 mm"],["Etiqueta máx.","360×360 mm"],["Potencia","6,5 kW"],["Peso","1.850 kg"]]},

// ============ RESMADORAS ============
{cat:"resmadoras", model:"DPR-1100H", tagline:"Resmadora para papel fino", desc:"Corta papel de embalaje, hamburguesa, laminado, impresión y compuestos plástico-papel en bobina.",
 badges:["30–200 veces/min","Precisión ±0,2 mm","Sencilla"],
 specs:[["Ancho máx. corte","1100 mm"],["Grosor material","20–500 g/m²"],["Potencia","20 kW"],["Peso","10.000 kg"]]},

// ============ CONTRACOLADORAS / ENCOLADORAS ============
{cat:"contracoladoras", model:"DPEFBK-800", tagline:"Contracoladora automática de cartoncillo (RFID)", desc:"Encolado de papel estucado; apta para etiquetas RFID, alimentos y embalaje textil.",
 badges:["15–50 piezas/min","Apilador automático","Gramaje 180–400 g/m²"],
 specs:[["Tamaño máx. encolado","750×540 mm"],["Potencia","11,65 kW"],["Peso","5.500 kg"],["Dimensiones","6800×2000×2300 mm"]]},
{cat:"contracoladoras", model:"DPC 1700D", tagline:"Contracoladora de alta velocidad", desc:"Encolado de cartón ondulado (3/5/7 capas) y cartón con cartón, gramajes >300 g/m².",
 badges:["189 m/min","Precisión ±1,5 mm","Más de 10 servomotores"],
 specs:[["Tamaño máx. pliego","1700×1650 mm"],["Potencia","22 kW"],["Peso","7.600 kg"],["Dimensiones","15600×2450×2600 mm"]]},
{cat:"contracoladoras", model:"DPES 1100D", tagline:"Encoladora semiautomática", desc:"Encolado de cartoncillo/papel para packaging y encuadernación; una sola persona la opera.",
 badges:["15–50 h/min","Precisión ±0,5 mm","Preparación rápida"],
 specs:[["Tamaño encolado","380×380 a 1100×650 mm"],["Gramaje","180–500 g/m²"],["Potencia","9 kW"],["Peso","4.000 kg"]]},
{cat:"contracoladoras", model:"DPC 1450 PRO", tagline:"Contracoladora automática gran formato", desc:"Alto rendimiento y precisión; adaptable a cartones, microcorrugados y otros sustratos.",
 badges:["150 m/min","Gran formato","Opcionales disponibles"],
 specs:[["Tamaño máx. pliego","1450×1450 a 1700×1650 mm"],["Potencia","22 kW"],["Peso","7.300–7.800 kg"],["Precisión","±1,5 mm"]]},
{cat:"contracoladoras", model:"DPEC", tagline:"Contracoladora / encoladora alta velocidad", desc:"Pegado de papel impreso sobre cartón; alimentación tipo 'escamas de pescado' estable.",
 badges:["13.000 pliegos/h","Laminador silencioso","Posicionamiento preciso"],
 specs:[["Tamaño máx. pliego","1500×1400 a 1700×1600 mm"],["Papel","150–800 g/m²"],["Potencia","28,5 kW"],["Peso","9.000–10.000 kg"]]},

// ============ FORRADORAS DE CAJAS ============
{cat:"forradoras", model:"DPFR-B500", tagline:"Forradora de cajas", desc:"Ajuste automático del molde vía pantalla táctil; doblado de esquinas automático.",
 badges:["0–25 cajas/min","2 kW","1.000 kg"],
 specs:[["Caja máx.","450×400×120 mm"],["Caja mín.","60×60×10 mm"],["Voltaje","220V 50Hz"],["Dimensiones","1500×1250×2000 mm"]]},
{cat:"forradoras", model:"DPFRRB 6040", tagline:"Forradora de cajas rígidas de lujo", desc:"Zapatos, ropa, joyería y regalos; pegado, esquinas y armado en un solo flujo continuo.",
 badges:["35 cajas/min","Precisión ±0,25 mm","PLC + fotoeléctrico"],
 specs:[["Altura máx. pila cajas","1.000 mm"],["Potencia","16,35 kW"],["Peso neto","5.800 kg"],["Dimensiones","6600×4100×3250 mm"]]},
{cat:"forradoras", model:"DPFRB 460", tagline:"Forradora de cajas semiautomática", desc:"Cajas de regalo y cubiertas preformadas; forrado sin arrugas ni marcas visibles.",
 badges:["10–16 uds/min","Sin arrugas","Programación personalizada"],
 specs:[["Caja máx.","400×320×1200 mm"],["Caja mín.","90×60×15 mm"],["Potencia","1,15 kW"],["Peso","500 kg"]]},
{cat:"forradoras", model:"DPFRQFM", tagline:"Forradora de cajas (carpetas y displays)", desc:"Detección por fibra óptica para carpetas, displays y cubiertas rígidas de gran formato.",
 badges:["0–30 uds/min","Corrección automática","Detección fibra óptica"],
 specs:[["Longitud papel","190–1030 mm"],["Espesor cartón","1–3 mm"],["Potencia","12–13 kW"],["Peso","3.500–4.500 kg"]]},
{cat:"forradoras", model:"DPFRCX 420", tagline:"Forradora de cajas automática", desc:"Forrado, doblado de esquinas y laterales en un ciclo; ideal cajas de regalo y cosmética.",
 badges:["20–38 uds/min","Sin burbujas","Cambio de moldes rápido"],
 specs:[["Caja máx.","420×300×70 mm"],["Caja mín.","100×50×15 mm"],["Potencia","1,15 kW"],["Peso","1.100 kg"]]},
{cat:"forradoras", model:"DPFRZK 320", tagline:"Forradora de cartón rígido", desc:"Joyería, cosmética y regalos; alimentación, adhesivo, forrado y prensado automatizados.",
 badges:["20–30 cajas/min","Precisión ±5 mm","Control táctil"],
 specs:[["Papel forrado","100–157 g/m²"],["Cartón rígido","0,8–2 mm"],["Potencia","22 kW"],["Peso","2.300 kg"]]},

// ============ MAQUINARIA PARA PACKAGING: FORMADORAS DE CAJAS ============
{cat:"formadoras", model:"DPFMZCHJ D120", tagline:"Formadora de bandejas de cartón", desc:"Bandejas alimentarias; control PLC sincroniza alimentación, calentamiento, moldeado y apilado.",
 badges:["25–50 pzs/min","Control mecánico estable","Formato adaptable"],
 specs:[["Material","200–400 g/m²"],["Potencia","3 kW"],["Peso","1.750 kg"],["Dimensiones","2800×1100×1700 mm"]]},
{cat:"formadoras", model:"DPFMHBJ D800", tagline:"Formadora de cajas de comida", desc:"Cajas, bandejas y envases desechables para hamburguesas, pollo, patatas y snacks.",
 badges:["50–180 pzs/min","Bajo mantenimiento","Cambio fácil de molde"],
 specs:[["Materiales","200–600 g/m²"],["Potencia","5–6,25 kW"],["Peso","1,8–2,5 T"],["Dimensiones","3600×1400–1850×1700 mm"]]},

// ============ MAQUINARIA PARA PACKAGING: MÁQUINAS DE VENTANAS ============
{cat:"ventanas", model:"DPPVTC 1100S", tagline:"Máquina de ventanas", desc:"Coloca ventanas de film en cajas (telefonía, bebidas, regalos, cosmética, alimentación).",
 badges:["Hasta 15.000 cajas/h","Precisión ±0,7 mm","Cartoncillo 200–1500 g/m²"],
 specs:[["Pliego máx.","1100×750 mm"],["Espesor film","0,08–0,3 mm"],["Potencia","9 kW"],["Peso","3.500 kg"]]},
{cat:"ventanas", model:"DPPVXLTC 1020", tagline:"Pegadora de ventanas", desc:"Pega film y hace ventanas en cajas de teléfonos, vinos, pañuelos, cosméticos y juguetes.",
 badges:["6.000 hojas/h","Dimensiones reducidas","Cartón ondulado ≤3 mm"],
 specs:[["Papel máx.","1080×650 mm"],["Cartoncillo","200–500 g/m²"],["Potencia","9 kW"],["Peso","2.850 kg"]]},

// ============ PEGADORAS DOBLADORAS ============
{cat:"pegadoras", model:"EQUIPO DE PLASMA (opcional)", tagline:"Opcional para pegadoras", desc:"Quemado controlado que mejora la adhesión en cajas plastificadas hasta un 30%.",
 badges:["+30% adhesión","1–3 pistolas","Instalación en línea"],
 specs:[["Voltaje","AC220V"],["Frecuencia plasma","20 kHz"],["Distancia trabajo","6–10 mm"],["Peso","50–70 kg"]]},
{cat:"pegadoras", model:"DPPYB MINI", tagline:"Pegadora dobladora compacta", desc:"Pegado y doblado lineal de estuches en espacio reducido; packaging digital.",
 badges:["0–220 m/min","Dimensiones MINI","Hasta 40.000 cajas/h"],
 specs:[["Apertura máx.","300×200 mm"],["Apertura mín.","65×50 mm"],["Papel","210–400 g/m²"],["Peso","1.000 kg"]]},
{cat:"pegadoras", model:"DPPZH", tagline:"Pegadora dobladora (formatos 800/1000)", desc:"Fondo automático; alimentación continua y correa múltiple con motor vibrante.",
 badges:["0–220 m/min","Full automática","Opcionales disponibles"],
 specs:[["Material","Cartoncillo 210–700 g/m²"],["Potencia","4,5 kW"],["Peso","2.000–2.200 kg"],["Adhesivo","Cola fría / base agua"]]},
{cat:"pegadoras", model:"DPPZH/BH", tagline:"Pegadora dobladora (formatos 650/850/1100)", desc:"Infrarrojos de seguridad; dobla cajas de 1, 3, 4 y 6 puntos.",
 badges:["Vel. 400 m/min","Full automática","Opcionales disponibles"],
 specs:[["Material","Cartón 210–850 g/m²"],["Consumo eléctrico","23 kW"],["Peso","8 T"],["Adhesivo","Cola fría"]]},

// ============ STAMPING ============
{cat:"stamping", model:"DPTSM", tagline:"Máquina de stamping manual", desc:"Troqueladora con stamping para cartón, hojas de plástico y productos de piel.",
 badges:["Sensores ópticos","Troquelado disponible","Preparación rápida"],
 specs:[["Tamaño chasis","1,60×1,25 m"],["Potencia motor","11 kW"],["Peso","12.000 kg"],["Longitud máx. regla","≤43 m"]]},
{cat:"stamping", model:"DPSATL 780RD", tagline:"Máquina de stamping (troquelado + hot stamping)", desc:"Troquelado, stamping caliente y pelado automáticos; control PLC avanzado.",
 badges:["2.800 hojas/h","Hasta 2.000 g/m²","Preparación 7 min"],
 specs:[["Hoja máx.","780×560 mm"],["Potencia","8–16 kW"],["Peso","6.000–7.500 kg"],["Ruido","<77 dB"]]},
{cat:"stamping", model:"DPSA Foil Tech", tagline:"Módulo universal — estampación en frío", desc:"Impresión y estampación en un mismo proceso; efecto dorado/plateado sin plancha caliente.",
 badges:["Hasta 12.000 pág/h","Estampación en frío","Colores diferentes"],
 specs:[["Vel. estampado caliente ref.","6.000 pág/h"],["Precisión líneas","0,05 mm"],["Modo","Automática"],["Uso","Papel y plástico"]]},
{cat:"stamping", model:"DPSA 76T", tagline:"Máquina de stamping (Hot Foil)", desc:"Troquelado y estampado con 10 zonas de calor independientes y 3 bobinas de foil.",
 badges:["7.000 pliegos/h","Presión 200 T","Dimensiones reducidas"],
 specs:[["Hoja máx.","760×600 mm"],["Zonas de calor","10"],["Potencia total","15–35 kW"],["Peso","13 T"]]},

// ============ IMPRESIÓN DIGITAL ============
{cat:"impresion", model:"2500S-PRO-8AX2", tagline:"Impresora digital single-pass", desc:"16 cabezales Epson piezoeléctricos en 8 colores; calidad fotográfica a escala industrial.",
 badges:["700 m²/h","Ancho 2450 mm","360×1200 dpi"],
 specs:[["Grosor material","1,5–35 mm"],["Cabezales","16 (opcional)"],["Potencia máx.","35 kW"],["Peso","10 T"]]},
{cat:"impresion", model:"DPID-2500S-16B", tagline:"Impresora digital single y multi-pass", desc:"Una pasada de alta velocidad + multipasada de alta resolución, hasta 2400 dpi.",
 badges:["≤72 m/min","Ancho 2500 mm","16 cabezales"],
 specs:[["Resolución multipasada","hasta 2400 dpi"],["Grosor material","1,5–35 mm"],["Potencia máx.","15 kW"],["Peso","5 T"]]},
{cat:"impresion", model:"DPCL-400", tagline:"Impresora digital de cantos de libro", desc:"4 a 8 inyectores piezoeléctricos; imprime cualquier gráfico en cantos de libros y cuadernos.",
 badges:["400 libros/h","Precisión ±0,02 mm","4 colores estándar"],
 specs:[["Espesor impresión","0–60 mm"],["Potencia","650 W"],["Peso","650 kg"],["Voltaje","110–220V"]]},
{cat:"impresion", model:"DPID-1800", tagline:"Impresora digital cartón corrugado", desc:"Impresión a todo color, single pass, sin fabricar planchas; datos variables (QR, series).",
 badges:["20–40 m/min","Single pass","Espumado térmico"],
 specs:[["Ancho impresión","1200 mm"],["Cabezales","4 (HP A3)"],["Grosor material","1,5–20 mm"],["Peso","3.000 kg"]]},
{cat:"impresion", model:"DPID-2500", tagline:"Impresora digital single pass", desc:"Mecanismo de un solo trazo; salida de color estable para grandes volúmenes.",
 badges:["20–40 m/min","Ancho 1500 mm","Tinta base agua"],
 specs:[["Cabezales","5 (HP A3)"],["Ancho alimentación","2500 mm"],["Grosor material","1,5–20 mm"],["Peso","4.000 kg"]]},
{cat:"impresion", model:"DPID-900", tagline:"Impresora digital cartón ondulado", desc:"Lotes pequeños sin planchas; alta resolución CMYK para cajas, bolsas de papel y pizza.",
 badges:["20–40 m/min","Ancho 900 mm","CMYK single pass"],
 specs:[["Cabezales","2 (HP A3)"],["Ancho impresión","600 mm"],["Grosor material","1,5–20 mm"],["Peso","500 kg"]]},

// ============ GUILLOTINAS ============
{cat:"guillotinas", model:"Línea de Corte a medida", tagline:"Guillotina + apilador + paletizador", desc:"Línea integrada configurable: corte, apilado automático y paletizado sin intervención manual.",
 badges:["A medida","Corte alta precisión","Apilado automático"],
 specs:[["Configuración","Modular a medida"],["Certificación","CE"],["Control","Micro-ordenador programable"],["Uso","Imprentas y packaging"]]},
{cat:"guillotinas", model:"DPG 260F", tagline:"Guillotina automática gran formato", desc:"Servo control digital japonés; 300 programas y más de 30.000 posiciones de corte.",
 badges:["Corte 260 cm","Memoria 300 trabajos","Autodiagnóstico"],
 specs:[["Vel. alimentación","8–30 m/min"],["Potencia motor","7,5 kW"],["Peso","13.000 kg"],["Presión máx. papel","70.000 N"]]},
{cat:"guillotinas", model:"DPG 166F", tagline:"Guillotina automática", desc:"Alta gama para grandes volúmenes; pantalla LCD 15\" y sistema hidráulico doble.",
 badges:["Corte 166 cm","Memoria 300 trabajos","Seguridad avanzada"],
 specs:[["Vel. alimentación","8–30 m/min"],["Potencia motor","5,5 kW"],["Peso","5.500 kg"],["Presión máx. papel","60.000 N"]]},
{cat:"guillotinas", model:"DPG 115F", tagline:"Guillotina automática", desc:"LCD táctil color, autodiagnóstico y 100 programas con 10.000 posiciones de corte.",
 badges:["Corte 115 cm","Memoria 500 trabajos","Vel. 5–18 m/min"],
 specs:[["Potencia motor","4 kW"],["Peso","4.600 kg"],["Presión máx. papel","40.000 N"],["Componentes","Italia/Francia/Japón/Corea"]]},
{cat:"guillotinas", model:"DPG 68E", tagline:"Guillotina automática (formato reducido)", desc:"Accionamiento hidráulico completo para pliegos pequeños con repetibilidad de corte.",
 badges:["Corte 68 cm","Memoria 500 trabajos","Pantalla táctil 10\""],
 specs:[["Potencia motor","1,5 kW"],["Peso","800 kg"],["Presión máx. papel","10.000 N"],["Vel. corte","20 r/min"]]},
{cat:"guillotinas", model:"DPG 52F", tagline:"Guillotina compacta monofásica", desc:"Totalmente hidráulica y monofásica (220V); ideal oficinas y pequeñas imprentas.",
 badges:["Corte 52 cm","Memoria 500 trabajos","Monofásica 220V"],
 specs:[["Potencia motor","—"],["Peso","370 kg"],["Presión máx. papel","7.000 N"],["Vel. corte","20 r/min"]]},

// ============ MAQUINARIA DE BOLSAS DE PAPEL ============
{cat:"bolsas", model:"DPBPG 4.0", tagline:"Máquina de bolsas de papel de lujo", desc:"Formado de una sola vez sin línea de plegado; cambio de molde en 30–60 min.",
 badges:["30–45 bolsas/min","Espesor 180–280 g","Opcionales disponibles"],
 specs:[["Ancho bolsa","180–500 mm"],["Altura bolsa","180–450 mm"],["Fuelle","70–200 mm"],["Long. asa","420–600 mm"]]},
{cat:"bolsas", model:"DPBPG 3.0", tagline:"Máquina de bolsas de lujo con asas", desc:"Formado, sellado y pegado en un proceso; cartulina blanca, dorada o plateada.",
 badges:["Hasta 50 bolsas/min","Preparación 7 min","Sencilla"],
 specs:[["Altura bolsa","240–450 mm"],["Ancho bolsa","240–500 mm"],["Gramaje papel","180–300 g"],["Pliegue fondo","Forma M"]]},
{cat:"bolsas", model:"DPBP A400S", tagline:"Máquina de bolsas con asas rizadas y planas", desc:"Formado de tubo, asas, fondo y corte en un proceso continuo; cambio de formato <2 min.",
 badges:["150–200 uds/min","Precisión ±0,5 mm","Servos japoneses"],
 specs:[["Ancho bobina","510/610–1230 mm"],["Espesor papel","80–140 g/m²"],["Potencia","38 kW"],["Peso","18.000 kg"]]},

// ============ ROBOTS INTELIGENTES: PEGADO ============
{cat:"robot-pegado", model:"Robot de Pegado DPRP CNC", tagline:"Mesa de pegado XY", desc:"Adhesivos termofusibles y fríos (PVA) de precisión sobre materiales para displays y PLV.",
 badges:["Vel. máx. 1,3 m/s","Formatos DXF/PLT/AI","Posicionamiento láser"],
 specs:[["Mesa 1813C","1800×1300 mm"],["Mesa 2516C","2500×1600 mm"],["Mesa 3020C","3000×2000 mm"],["Elevación","Automática"]]},
{cat:"robot-pegado", model:"DPKZHJ", tagline:"Plóter de pegado", desc:"Aplicación de cola caliente sobre cartón; coordenadas programables o dibujo directo.",
 badges:["Área 1000×750 mm","Presión 6–8 bar","Potencia 2 kW"],
 specs:[["Papel máx.","1200×900 mm"],["Espesor papel","100–200 mm"],["Peso","700 kg"],["Dimensiones","1560×1290×1520 mm"]]},

// ============ ROBOTS INTELIGENTES: CORTE ============
{cat:"robot-corte", model:"DPFAKLZ", tagline:"Plóter de corte / fresadora automática", desc:"Hendido en V de cartoncillo, chipboard, cartón ondulado y MDF; sin polvo ni rebabas.",
 badges:["100–120 pzs/min","Precisión ±0,05 mm","12 cuchillas"],
 specs:[["Ancho cartoncillo","100–850 mm"],["Espesor","200 g/m² a 3,5 mm"],["Potencia","3,5 kW"],["Travesaños","2"]]},

// ============ COMPRESORES ============
{cat:"compresores", model:"DPCA PM VSD", tagline:"Compresor de tornillo (imanes permanentes)", desc:"Motor PM con variador integrado; ahorro energético de hasta 35% frente a velocidad fija.",
 badges:["7,5–250 kW","Ahorro hasta 35%","Autodiagnóstico"],
 specs:[["Caudal","1,1–43,8 m³/min"],["Presión","7–10 bar"],["Ruido","60–85 dB"],["Gama","10–350 HP"]]},
{cat:"compresores", model:"Compresor Tornillo para Láser", tagline:"Compresor de tornillo industrial", desc:"Misma gama PM-VSD adaptada a aplicaciones de corte láser y producción continua 24/7.",
 badges:["7,5–250 kW","Transmisión directa","Disponibilidad 24/7"],
 specs:[["Caudal","1,1–43,8 m³/min"],["Presión","7–10 bar"],["Ruido","60–85 dB"],["Gama","10–350 HP"]]},
{cat:"compresores", model:"Serie Laser-PV/20", tagline:"Compresor de tornillo alta presión (corte láser)", desc:"20 bar constantes, filtración 0,001 µm; protege la óptica y sustituye gases auxiliares.",
 badges:["20 bar","Filtración 0,001 µm","Doble depósito 1200 L"],
 specs:[["Potencia","22–37 kW"],["Flujo aire","1,92–3,4 m³/min"],["Gama","30–50 HP"],["Instalación","Plug & play"]]},

// ============ MAQUINARIA AUXILIAR ============
{cat:"auxiliar", model:"Elevador de Bobinas (DPEB)", tagline:"Accesorio para laminadoras", desc:"Eleva y posiciona bobinas de forma automatizada evitando lesiones en su manipulación.",
 badges:["Hasta 1.000 kg","Mando extensible","24V"],
 specs:[["Peso permitido","1.000 kg"],["Voltaje","24V"],["Elevador","Por cadena"],["Uso","Laminadoras"]]},
{cat:"auxiliar", model:"Peladora Neumática", tagline:"Herramienta de pelado de precisión", desc:"Cuerpo de acero inoxidable, mango ergonómico; ideal industria cárnica o alimentaria.",
 badges:["2.500 RPM","Compacta 6 kg","Alta presión 6 bar"],
 specs:[["Aire comprimido","11 L/s"],["Toma de aire","8×12 mm"],["Peso","6 kg"],["Mantenimiento","Bajo"]]},
{cat:"auxiliar", model:"DPDF 10B", tagline:"Cortadora de fleje para troqueles", desc:"Doblado, punzonado, rebordeado e indentación de flejes con programación rápida.",
 badges:["Control automático","Preparación rápida","Opcionales disponibles"],
 specs:[["Espesor eje","0,71–1,07 mm"],["Formatos archivo","DXF/DWG/AI/CDR/PLT"],["Potencia","2 kW"],["Peso","520 kg"]]},
{cat:"auxiliar", model:"DPVP PRO", tagline:"Formadora de vasos de papel", desc:"Sellado ultrasónico; producción media para hostelería, bebidas para llevar y eventos.",
 badges:["70–85 uds/min","Sellado ultrasónico","Alarma inteligente"],
 specs:[["Tamaño vaso","2,5–12 oz"],["Papel","150–380 g/m²"],["Potencia","5 kW"],["Peso","2.350 kg"]]},
{cat:"auxiliar", model:"DPEVH 1070", tagline:"Compactadora hidráulica", desc:"Prensa residuos de papel, cartón, plástico, botellas, lana, heno y telas.",
 badges:["30–40 T fuerza","3–6 pacas/h","Estándar europeo"],
 specs:[["Peso pacas","150–350 kg"],["Potencia","5,5 kW"],["Peso máquina","1.200–1.700 kg"],["Apertura alim.","1050×500 mm"]]},
{cat:"auxiliar", model:"DPCHM", tagline:"Cortadora de hendidos manual", desc:"Accionador de palanca y regla milimetrada para contrahendidos de troqueles planos.",
 badges:["Accionamiento manual","Regla graduada","Portátil"],
 specs:[["Uso","Tiras de canal / PVC / PET"],["Alimentación","No requiere"],["Estructura","Metálica"],["Ahorro material","Alto"]]},
{cat:"auxiliar", model:"DPPE 655", tagline:"Precintadora automática", desc:"Doble columna, sellado en 'H'; ajustable a múltiples tamaños de caja.",
 badges:["Hasta 600 cajas/h","18 m/min","Sellado tipo H"],
 specs:[["Caja","200–600 × 150–500 × 150–500 mm"],["Voltaje","110/220V"],["Cinta compatible","48/60/75 mm"],["Peso","270 kg"]]},
{cat:"auxiliar", model:"DPTI", tagline:"Transpaleta inteligente", desc:"Transpaleta + elevador automático por sensor fotoeléctrico; reduce lesiones de espalda.",
 badges:["Carga 1.000 kg","Altura 85–800 mm","Batería 60Ah/12V"],
 specs:[["Ancho","540 mm"],["Longitud","1160 mm"],["Peso neto","160 kg"],["Elevación","Eléctrica"]]},

// ============ OCASIÓN / SEGUNDA MANO ============
{cat:"ocasion", model:"Forradora Dobladora Tapa Dura", tagline:"Ocasión — con robot de forrado", desc:"Máquina automática con robot para forrado de tapa dura; disponible en Barcelona para ver en producción.",
 badges:["Segunda mano","Disponible en Barcelona","Vídeo bajo petición"],
 specs:[["Estado","Producción profesional"],["Ubicación","Barcelona"],["Info técnica","Bajo consulta"],["Consulta","Contactar"]]},
{cat:"ocasion", model:"Recogedor Automático de Cajas", tagline:"Ocasión", desc:"Muy buen estado y funcionando perfectamente; entrega inmediata.",
 badges:["Segunda mano","Entrega inmediata","Muy buen estado"],
 specs:[["Estado","Excelente"],["Disponibilidad","Inmediata"],["Info técnica","Bajo consulta"],["Consulta","Contactar"]]},
{cat:"ocasion", model:"CTP Heidelberg", tagline:"Ocasión — año 2006", desc:"CTP de segunda mano de la marca Heidelberg, revisado y en perfecto funcionamiento.",
 badges:["Segunda mano","Año 2006","Marca Heidelberg"],
 specs:[["Marca","Heidelberg"],["Año","2006"],["Estado","Muy buena calidad"],["Visita","Nave disponible"]]},
{cat:"ocasion", model:"PAPERPLAST 1400", tagline:"Ocasión — laminadora dry 70", desc:"Plastificadora térmica de doble cara con 2 circuladores de aceite caliente Coremi.",
 badges:["Segunda mano","Vel. máx. 70 m/min","Doble cara"],
 specs:[["Hoja máx.","76×104 cm"],["Hoja mín.","46×38 cm"],["Alimentador","Samal"],["Apilador","Con enfriador TAE"]]},

];

const CATEGORY_LABELS = {
 "laminado":"Laminado / Plastificadoras",
 "barnizado":"Barnizadoras",
 "troquelado":"Troqueladoras",
 "robots-pelado":"Robots de Pelado",
 "resmadoras":"Resmadoras",
 "contracoladoras":"Contracoladoras / Encoladoras",
 "forradoras":"Forradoras de Cajas",
 "formadoras":"Formadoras de Cajas / Bandejas",
 "ventanas":"Máquinas de Ventanas",
 "pegadoras":"Pegadoras Dobladoras",
 "stamping":"Stamping",
 "impresion":"Impresión Digital",
 "guillotinas":"Guillotinas",
 "bolsas":"Maquinaria de Bolsas de Papel",
 "robot-pegado":"Robots Inteligentes — Pegado",
 "robot-corte":"Robots Inteligentes — Corte",
 "compresores":"Compresores",
 "auxiliar":"Maquinaria Auxiliar",
 "ocasion":"Ocasión / Segunda Mano",
};
