// Imágenes (foto principal de la ficha, alojadas junto al artefacto) y vídeo de YouTube (cuando existe) por modelo.
const MEDIA = {
"DPLASW 560/660/760": {img:"images/dplasw-560.png", yt:"h3pWjJN6IEY"},
"DPLASWAFM 1050/820": {img:"images/dplaswafm-1050.png", yt:null},
"DPLASW 1080": {img:"images/dplasw-1080.png", yt:"UGcro7c5dj8"},
"DPLA Serie G": {img:"images/dpla-serie-g.png", yt:"7dfjvuC-uPI"},
"DPLASF 720C": {img:"images/dplasf-720c.png", yt:"9W2W2uQrRsg"},
"DPLAGL 1080": {img:"images/dplagl-1080.png", yt:"I9-PRbe7xDE"},
"DPLA-2020B": {img:"images/dpla-2020b.png", yt:null},
"Barnizadora DPBGV 1080": {img:"images/dpbgv-1080.png", yt:"8RC0FCtiefo"},
"Barnizadora DPIST-105 GS": {img:"images/dpist-105gs.png", yt:null},
"Troqueladora DPTA-1060H": {img:"images/dpta-1060h.png", yt:"fwYuGv9iXSA"},
"DPTAJY 106EBR": {img:"images/dptajy-106eb.png", yt:null},
"DPTAZHM 1670QE": {img:"images/dptazhm-1670qe.png", yt:null},
"Máquina Automática para Cortar Hendidos (DPCH-C3)": {img:"images/dpch-c3.png", yt:"_nQvvjtUkZw"},
"9000 PRO": {img:"images/troq-9000pro.png", yt:"3XxmSksWvTI"},
"DPTASM 1020": {img:"images/dptasm-1020.png", yt:"rI8AXswbk3o"},
"DPTASM 1080": {img:"images/dptasm-1080.png", yt:"5NltkzMgleU"},
"DPR-1100H": {img:"images/dpr-1100h.png", yt:"GwBIdYR1WC0"},
"DPEFBK-800": {img:"images/dpefbk-800.png", yt:null},
"DPC 1700D": {img:"images/dpc-1700d.png", yt:"iaoUaik0FkY"},
"DPES 1100D": {img:"images/dpes-1100d.png", yt:"X0qpphrM0js"},
"DPC 1450 PRO": {img:"images/dpc-1450pro.png", yt:"yGNNE_eA8R8"},
"DPEC": {img:"images/dpec.png", yt:"a60e1iaMDMs"},
"DPFR-B500": {img:"images/dpfr-b500.png", yt:"GukQqmvF_5I"},
"DPFRRB 6040": {img:"images/dpfrrb-6040.png", yt:null},
"DPFRB 460": {img:"images/dpfrb-460.png", yt:"-jfn5edr7ks"},
"DPFRQFM": {img:"images/dpfrqfm.png", yt:null},
"DPFRCX 420": {img:"images/dpfrcx-420.png", yt:null},
"DPFRZK 320": {img:"images/dpfrzk-320.png", yt:null},
"DPFMZCHJ D120": {img:"images/dpfmzchj-d120.png", yt:"VSoxZc33i4w"},
"DPFMHBJ D800": {img:"images/dpfmhbj-d800.png", yt:null},
"DPPVTC 1100S": {img:"images/dppvtc-1100s.png", yt:"cccgmWkZ684"},
"DPPVXLTC 1020": {img:"images/dppvxltc-1020.png", yt:null},
"EQUIPO DE PLASMA (opcional)": {img:"images/equipo-plasma.png", yt:null},
"DPPYB MINI": {img:"images/dppyb-mini.png", yt:null},
"DPPZH": {img:"images/dppzh.png", yt:null},
"DPPZH/BH": {img:"images/dppzh-bh.png", yt:"Hgh60_mkIF4"},
"DPTSM": {img:"images/dptsm.png", yt:null},
"DPSATL 780RD": {img:"images/dpsatl-780rd.png", yt:null},
"DPSA Foil Tech": {img:"images/dpsa-foiltech.png", yt:"EKXfd5Qor_E"},
"DPSA 76T": {img:"images/dpsa-76t.png", yt:null},
"2500S-PRO-8AX2": {img:"images/imp-2500spro8ax2.png", yt:"yLte0D02jso"},
"DPID-2500S-16B": {img:"images/dpid-2500s-16b.png", yt:"yjkZZlqgWg8"},
"DPCL-400": {img:"images/dpcl-400.png", yt:"aej1JT6oHOg"},
"DPID-1800": {img:"images/dpid-1800.png", yt:"CXhV5B4cMb0"},
"DPID-2500": {img:"images/dpid-2500.png", yt:"Wx6U8Qs86SM"},
"DPID-900": {img:"images/dpid-900.png", yt:null},
"Línea de Corte a medida": {img:"images/linea-de-corte.png", yt:null},
"DPG 260F": {img:"images/dpg-260f.png", yt:null},
"DPG 166F": {img:"images/dpg-166f.png", yt:null},
"DPG 115F": {img:"images/dpg-115f.png", yt:null},
"DPG 68E": {img:"images/dpg-68e.png", yt:null},
"DPG 52F": {img:"images/dpg-52f.png", yt:null},
"DPBPG 4.0": {img:"images/dpbpg-4-0.png", yt:null},
"DPBPG 3.0": {img:"images/dpbpg-3-0.png", yt:null},
"DPBP A400S": {img:"images/dpbp-a400s.png", yt:null},
"Robot de Pegado DPRP CNC": {img:"images/robot-pegado-dprp.png", yt:"UMM5PaCUa8Y"},
"DPKZHJ": {img:"images/dpkzhj.png", yt:"Sa3hLYSNAgY"},
"DPFAKLZ": {img:"images/dpfaklz.png", yt:"DScwPcAd7kA"},
"DPCA PM VSD": {img:"images/dpca-pm-vsd.png", yt:null},
"Compresor Tornillo para Láser": {img:"images/compresor-laser.png", yt:null},
"Serie Laser-PV/20": {img:"images/serie-laser-pv20.png", yt:null},
"Elevador de Bobinas (DPEB)": {img:"images/elevador-bobinas.png", yt:"fsp1v3BaXCA"},
"Peladora Neumática": {img:"images/peladora-neumatica.png", yt:null},
"DPDF 10B": {img:"images/dpdf-10b.png", yt:"EAFt0B21H5M"},
"DPVP PRO": {img:"images/dpvp-pro.png", yt:null},
"DPEVH 1070": {img:"images/dpevh-1070.png", yt:null},
"DPCHM": {img:"images/dpchm.png", yt:null},
"DPPE 655": {img:"images/dppe-655.png", yt:"vOo8QLKO5cU"},
"DPTI": {img:"images/dpti.png", yt:"dQnlCNjxlMU"},
"Forradora Dobladora Tapa Dura": {img:"images/forradora-tapa-dura.png", yt:null},
"Recogedor Automático de Cajas": {img:"images/recogedor-cajas.png", yt:null},
"CTP Heidelberg": {img:"images/ctp-heidelberg.png", yt:null},
"PAPERPLAST 1400": {img:"images/paperplast-1400.jpg", yt:null},
};
